### ISSUE TITLE
Can't find the .cls extension on string

### ISSUE THREAD

**Issue by benjaminjackman** [com-lihaoyi/scalatags#55]
Hey Haoyi,

Trying to throw together a visualization using scalatags and was trying to use the 
"content".cls style of classes as seen here: https://github.com/lihaoyi/scalatags#layouts

Here is the my block of code:

``` scala
    import scalatags.JsDom._
    import scalatags.JsDom.all._
    val lvl = item.s
    var e = div(cls := "elscope-item", lvl.qtyIncs.toString)
    e = if (lvl.isMd) {
      if (lvl.mdSide.isBid)
        e("bid".cls)
      else
        e("ask".cls)
    } else {
      e("trade".cls)
    }
    e.render
```

Yes, I am using a var...
![yes I am using a var](http://i.imgur.com/ul917r8.png)

...anyhow I am getting cls is not a member of String

I searched through the scalatags repo and couldn't find a "def cls" or "val cls" which would be needed in the implicit extension class anywhere (except in the readme).

a. What import do i need? 
(a2 I think the code snippets should always have the imports listed at the top, the code snippets should work in isolation, i know the imports are a bit ugly but they really help to have them in each code block so that each one stands on it's own)
b. How can I make an string => class without using the implicit .cls?
c. I am assuming that this will append the class to the list of classes for the element rather than replacing all of them, am I right in this assumption?
